import type { Metadata } from "next";
import Link from "next/link";
import { Button, Container, Eyebrow } from "@/components/ui";

export const revalidate = 604800;
export const metadata: Metadata = { title: "Per Diem Software for Bookkeepers & Travel Teams", description: "Collect GSA per diem and IRS mileage records from every traveller in one reviewable team ledger, with export-ready reports.", alternates: { canonical: "/for/bookkeepers" } };

export default function BookkeepersPage() {
  return <Container className="py-14 sm:py-20"><div className="mx-auto max-w-4xl"><Eyebrow>For bookkeepers & finance teams</Eyebrow><h1 className="mt-4 max-w-3xl font-display text-4xl font-semibold leading-tight tracking-tight text-ink sm:text-6xl">Stop reconciling travel claims from six different spreadsheets.</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted">PerDiemWise gives each traveller a place to save the actual trip, while your team workspace brings the records back into one review queue.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/team" size="lg">Open team workspace</Button><Button href="/pricing" variant="outline" size="lg">See plans</Button></div><div className="mt-14 grid gap-4 md:grid-cols-3"><Feature title="Collect" text="Travellers save per diem, mileage and driver records from the same calculators they already use." /><Feature title="Review" text="See member trip totals together, with the source dates and record type attached." /><Feature title="Report" text="Build one export-ready report from the cloud ledger instead of re-keying every claim." /></div><div className="mt-14 rounded-2xl border border-line bg-paper-2/40 p-6"><p className="font-mono text-xs uppercase tracking-[0.14em] text-muted">Team subscription</p><h2 className="mt-2 font-display text-2xl font-semibold text-ink">Designed for recurring monthly work</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted">Team billing is configured through a real Stripe price, not a made-up amount. If the team price is not yet present in production, the workspace remains usable and checkout reports that configuration state clearly.</p><Link href="mailto:hello@perdiemwise.com" className="mt-4 inline-block text-sm font-medium text-accent hover:underline">Ask about team pricing →</Link></div></div></Container>;
}

function Feature({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-line bg-surface p-5"><h2 className="font-display text-xl font-semibold text-ink">{title}</h2><p className="mt-2 text-sm leading-relaxed text-muted">{text}</p></div>; }
